import { StyleSheet, Dimensions } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    position: 'absolute',
    top: 0,
    left: 0,
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(0,0,0,0.2)',
    zIndex: 100,
  },
  sectionHeaderText: {
    fontSize: 20,
    fontFamily: 'san-francisco-semibold',
    margin: 20,
  },
  ticketListContainer: {
    display: 'flex',
    flexDirection: 'row',
    overflow: 'scroll',
  },
  ticketContainer: {
    display: 'flex',
    flexDirection: 'row',
    width: Dimensions.get('window').width,
    justifyContent: 'center',
    paddingBottom: 3,
  },
  ticketOutline: {
    display: 'flex',
    flexDirection: 'column',
    width: Dimensions.get('window').width - 80,
    borderRadius: 8,
    shadowOpacity: 0.5,
    shadowColor: 'rgb(0,0,0)',
    shadowRadius: 1,
    shadowOffset: { width: 0, height: 0 },
    backgroundColor: '#fff',
  },
  ticketVenueImageContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
  },
  ticketVenueImage: {
    width: '100%',
    height: 200,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  ticketInfoContainer: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    paddingTop: 10,
  },
  ticketVenueText: {
    textAlign: 'center',
    fontSize: 20,
    fontFamily: 'san-francisco-semibold',
  },
  ticketDetailsText: {
    paddingTop: 3,
    textAlign: 'center',
    fontSize: 16,
    fontFamily: 'san-francisco',
  },
  ticketQrContainer: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'center',
    marginTop: -10,
    zIndex: -10,
  },
  redeemedTicketListContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: Dimensions.get('window').width,
  },
  redeemedTicketContainer: {
    display: 'flex',
    flexDirection: 'column',
    width: Dimensions.get('window').width - 80,
    padding: 8,
    borderRadius: 2,
    shadowOpacity: 0.5,
    shadowColor: 'rgb(0,0,0)',
    shadowRadius: 1,
    shadowOffset: { width: 0, height: 0 },
    backgroundColor: '#fff',
  },
});
